import { LayoutDashboard, Users, GraduationCap, BookOpen, Library, CalendarDays, ChartNoAxesCombined, FileText, Settings, Play, ClipboardCheck, ShieldCheck, Activity, Bell, Sparkles, UserRound, Monitor, KeyRound } from 'lucide-react';
export type Role = 'admin' | 'teacher' | 'student';
export const roles: Role[] = ['admin', 'teacher', 'student'];
export const navigation = {
 admin: [ ['dashboard','Overview',LayoutDashboard], ['students','Students',Users], ['teachers','Teachers',GraduationCap], ['classes','Classes',BookOpen], ['subjects','Subjects',Library], ['faculty-allocation','Faculty Allocation',CalendarDays], ['analytics','Analytics',ChartNoAxesCombined], ['reports','Reports',FileText], ['settings','Settings',Settings] ],
 teacher: [ ['dashboard','Overview',LayoutDashboard], ['my-classes','My Classes',BookOpen], ['start-class','Start Class',Play], ['attendance','Attendance',ClipboardCheck], ['classroom-control','Classroom Control',ShieldCheck], ['live-activity','Live Activity',Activity], ['alerts','Alerts',Bell], ['ai-reports','AI Reports',Sparkles], ['my-schedule','My Schedule',CalendarDays], ['profile','Profile',UserRound] ],
 student: [ ['dashboard','Overview',LayoutDashboard], ['my-classes','My Classes',BookOpen], ['current-session','Current Session',Monitor], ['permissions','Permissions',KeyRound], ['activity','Activity',Activity], ['notifications','Notifications',Bell], ['profile','Profile',UserRound] ],
} as const;
export const descriptions: Record<string,string> = {
 dashboard:'A clear view of your institution, all in one place.', students:'Manage your student directory and class enrollment.', teachers:'Your faculty directory and teaching assignments.', classes:'Organize classes across your institution.', subjects:'Manage your institution’s academic subjects.', 'faculty-allocation':'Bring the right teachers, classes, and subjects together.', analytics:'Understand attendance and classroom engagement.', reports:'Your institution’s classroom reports, organized.', settings:'Manage your institution’s workspace preferences.', 'my-classes':'Your classes and the people learning together.', 'start-class':'Prepare your next classroom session.', attendance:'Review attendance, one class at a time.', 'classroom-control':'Manage application permissions during a session.', 'live-activity':'A view of student activity during class.', alerts:'Classroom events that need your attention.', 'ai-reports':'Classroom insights, ready for your review.', 'my-schedule':'Your teaching week at a glance.', profile:'Your personal details and account preferences.', 'current-session':'Your classroom session and attendance status.', permissions:'Application access for your current class.', activity:'Your classroom activity history.', notifications:'Updates from your classes and institution.'
};
export const classSamples = [
 {name:'Computer Science', subject:'Data Structures & Algorithms', teacher:'Olivia Martin', initials:'OM', color:'mint', time:'09:00 – 10:00', room:'Room 204', students:32, status:'In progress'},
 {name:'Mathematics', subject:'Linear Algebra', teacher:'James Wilson', initials:'JW', color:'lavender', time:'10:30 – 11:30', room:'Room 108', students:28, status:'Upcoming'},
 {name:'Physics', subject:'Applied Mechanics', teacher:'Sophia Chen', initials:'SC', color:'peach', time:'11:45 – 12:45', room:'Lab 302', students:30, status:'Upcoming'},
 {name:'English Literature', subject:'Modern Literature', teacher:'Ethan Davis', initials:'ED', color:'blue', time:'14:00 – 15:00', room:'Room 112', students:26, status:'Upcoming'}
] as const;
export function pageMeta(title:string,description:string) { return {meta:[{title:`${title} — IntelliClass`},{name:'description',content:description},{property:'og:title',content:`${title} — IntelliClass`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}; }
