import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { Search, Plus, Filter, ArrowRight, BookOpen, Users, GraduationCap, Library, CalendarDays, FileText, ShieldCheck, Activity, Bell, Sparkles, Play, ClipboardCheck, Clock3, Monitor, Save, Download, CircleHelp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { navigation, descriptions, type Role } from '@/lib/intelliclass';
import { ConnectedDashboard } from './connected-dashboard';
import { AuthenticatedWorkspaceShell as WorkspaceShell } from './authenticated-workspace-shell';
import { EmptyState, Field, Panel, DataTable, StatusBadge } from './shared';
import { useNavigate } from '@tanstack/react-router';
import { useAuth } from './auth-provider';
import { ConnectedDirectory } from './connected-directory';
import { InstitutionSetup } from './institution-setup';
import { SessionWorkspace } from './session-workspace';
const directories:Record<string,{name:string;plural:string;headers:string[];icon:typeof Users}>={students:{name:'student',plural:'students',headers:['Student','Student ID','Class','Status'],icon:Users},teachers:{name:'teacher',plural:'teachers',headers:['Teacher','Department','Assigned classes','Status'],icon:GraduationCap},classes:{name:'class',plural:'classes',headers:['Class','Subject','Teacher','Students','Status'],icon:BookOpen},subjects:{name:'subject',plural:'subjects',headers:['Subject','Subject code','Department','Classes'],icon:Library},'faculty-allocation':{name:'allocation',plural:'allocations',headers:['Teacher','Class','Subject','Schedule','Status'],icon:CalendarDays},'my-classes':{name:'class',plural:'classes',headers:['Class','Subject','Teacher','Schedule','Status'],icon:BookOpen}};
function accountRole(role: string): Role | null {
 return role==='SUPER_ADMIN'||role==='INSTITUTION_ADMIN'?'admin':role==='TEACHER'?'teacher':role==='STUDENT'?'student':null;
}
export function WorkspacePage({role,page}:{role:Role;page:string}){
 const {user,state}=useAuth(); const navigate=useNavigate();
 useEffect(()=>{
  if(state==='signed-out') void navigate({to:'/login',replace:true});
  else if(state==='signed-in'&&user){
   const actual=accountRole(user.role);
   const destination=actual==='admin'?'/admin/dashboard':actual==='teacher'?'/teacher/dashboard':actual==='student'?'/student/dashboard':'/login';
   if(actual!==role) void navigate({to:destination,replace:true});
  }
 },[navigate,role,state,user]);
 if(state!=='signed-in'||!user||accountRole(user.role)!==role) return <div className="flex min-h-screen items-center justify-center bg-background text-muted-foreground" role="status">{state==='signed-out'?'Redirecting to sign in…':'Loading your secure workspace…'}</div>;
 const connectedPages=['students','teachers','classes','subjects','my-classes'];
 const sessionPages=['start-class','attendance','my-schedule','current-session'];
 return <WorkspaceShell role={role}>{page==='dashboard'?<ConnectedDashboard role={role}/>:page==='settings'?<InstitutionSetup/>:connectedPages.includes(page)?<ConnectedDirectory page={page} role={role}/>:sessionPages.includes(page)?<SessionWorkspace page={page} role={role}/>:<PageContent role={role} page={page}/>}</WorkspaceShell>
}
function PageContent({role,page}:{role:Role;page:string}){
 const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [dialog,setDialog]=useState(false); const [notice,setNotice]=useState(false); const [tab,setTab]=useState('All'); const [month,setMonth]=useState('October 2026');
 const title=navigation[role].find(i=>i[0]===page)?.[1]??page; const dir=directories[page];
 const report=['reports','ai-reports'].includes(page); const feed=['alerts','notifications','activity','live-activity'].includes(page);
 return <><div className="page-heading"><div><div className="eyebrow">{role.toUpperCase()} WORKSPACE</div><h1>{title}<span className="heading-dot">.</span></h1><p>{descriptions[page]}</p></div><div className="heading-actions"><StatusBadge>Not connected</StatusBadge>{dir&&role==='admin'&&<Button onClick={()=>setDialog(true)}><Plus/>{page==='faculty-allocation'?'Allocate faculty':`Add ${dir.name}`}</Button>}{report&&<Button disabled><Download/>Export reports</Button>}</div></div>
 {dir ? <Panel title={page==='faculty-allocation'?'Teaching assignments':title} subtitle="0 records"><div className="table-toolbar"><label className="search-input"><Search size={17}/><input placeholder={`Search ${dir.plural}…`} value={query} onChange={e=>setQuery(e.target.value)}/></label><select className="compact-select" aria-label="Filter records" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All {dir.plural}</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><DataTable headers={dir.headers}><tr><td colSpan={dir.headers.length}><EmptyState icon={dir.icon} title={query?`No results for “${query}”`:`No ${dir.plural} yet`} description={query?'Try a different search or clear your filters.':role==='admin'?`Your ${dir.plural} will appear here once institution data is connected.`:'Your assigned classes will appear here once your institution is connected.'}>{query&&<Button variant="outline" onClick={()=>setQuery('')}>Clear search</Button>}{!query&&role==='admin'&&<Button variant="outline" onClick={()=>setDialog(true)}><Plus/>{page==='faculty-allocation'?'Allocate faculty':`Add ${dir.name}`}</Button>}</EmptyState></td></tr></DataTable><div className="table-footer"><span>0 {dir.plural}</span><span>Page 1 of 1 <Button size="sm" variant="outline" disabled>Previous</Button><Button size="sm" variant="outline" disabled>Next</Button></span></div></Panel>
 :page==='profile'||page==='settings'? <div className="settings-layout"><nav className="settings-tabs">{(page==='profile'?['Personal details','Preferences']:['Institution','Preferences']).map(x=><Button variant={tab===x||tab==='All'&&x===(page==='profile'?'Personal details':'Institution')?'secondary':'ghost'} key={x} onClick={()=>setTab(x)}>{x}</Button>)}</nav><Panel title={tab==='All'?(page==='profile'?'Personal details':'Institution details'):tab} subtitle="Changes can be saved after your workspace is connected."><form className="settings-form" onSubmit={e=>{e.preventDefault();setNotice(true)}}>{tab==='Preferences'?<><Field label="Language"><select defaultValue="English"><option>English</option></select></Field><Field label="Time zone"><select defaultValue="Institution default"><option>Institution default</option><option>UTC</option></select></Field><Field label="Email notifications"><select><option>Enabled</option><option>Disabled</option></select></Field></>:<><div className="profile-placeholder"><span className="avatar large">{role.slice(0,2).toUpperCase()}</span><div><strong>{page==='settings'?'Your institution':'Your account'}</strong><p>No account connected</p></div></div><div className="form-grid"><Field label={page==='settings'?'Institution name':'Display name'}><input placeholder={page==='settings'?'Institution name':'Your name'}/></Field><Field label="Email address"><input type="email" placeholder="name@institution.edu"/></Field><Field label={page==='settings'?'Academic year':'Role'}><input placeholder={page==='settings'?'e.g. 2026–2027':role} readOnly={page==='profile'}/></Field><Field label="Department"><input placeholder="Department name"/></Field></div></>}<div className="form-bottom"><p>No changes have been saved.</p><Button type="submit"><Save/>Save changes</Button></div></form></Panel></div>
 :page==='start-class'?<div className="two-columns"><Panel title="Session details" subtitle="Prepare a session for an assigned class."><form className="settings-form" onSubmit={e=>{e.preventDefault();setNotice(true)}}><Field label="Class"><select disabled><option>No assigned classes</option></select></Field><Field label="Subject"><select disabled><option>Select a class first</option></select></Field><Field label="Session topic"><input placeholder="What are you teaching today?"/></Field><div className="form-grid"><Field label="Duration"><select><option>60 minutes</option><option>45 minutes</option><option>90 minutes</option></select></Field><Field label="Room"><input placeholder="Room or lab number"/></Field></div><Button disabled className="self-start"><Play/>Start session</Button></form></Panel><Panel title="Session readiness"><div className="readiness"><div><BookOpen/><span>Class selected</span><StatusBadge>Pending</StatusBadge></div><div><Users/><span>Student enrollment</span><StatusBadge>Pending</StatusBadge></div><div><Monitor/><span>Device connection</span><StatusBadge>Not connected</StatusBadge></div></div><EmptyState title="Ready when your class is" description="An assigned class and connected devices are required to start a session." icon={Play}/></Panel></div>
 :page==='analytics'?<><div className="stats-grid">{['Average attendance','Classroom engagement','Sessions completed','Active students'].map((x,i)=><article key={x} className="stat-card"><div className="stat-top"><span>{x}</span><span className={`stat-icon tone-${['mint','lavender','peach','blue'][i]}`}><Activity size={18}/></span></div><strong>—</strong><p>Waiting for institution data</p></article>)}</div><Panel title="Attendance trends" action={<select aria-label="Analytics period" className="compact-select"><option>This month</option><option>This semester</option></select>}><EmptyState title="Insights start with your first session" description="Attendance and engagement trends will appear when classroom data is connected." icon={Activity}/></Panel></>
 :page==='my-schedule'?<Panel title="Teaching schedule" action={<select aria-label="Schedule month" value={month} onChange={e=>setMonth(e.target.value)} className="compact-select"><option>October 2026</option><option>November 2026</option><option>December 2026</option></select>}><div className="calendar-week">{['Monday','Tuesday','Wednesday','Thursday','Friday'].map((d,i)=><div key={d}><span>{d}</span><strong>{12+i}</strong><p>No sessions</p></div>)}</div><EmptyState title="Your schedule is open" description="Teaching assignments will appear here when faculty allocation is connected." icon={CalendarDays}/></Panel>
 :page==='attendance'||page==='classroom-control'||page==='permissions'||page==='current-session'?<Panel title={page==='attendance'?'Session attendance':page==='classroom-control'?'Application permissions':page==='permissions'?'Your application access':'Session status'} action={<StatusBadge>No active session</StatusBadge>}>{page==='attendance'&&<div className="table-toolbar"><select className="compact-select" disabled><option>No classes available</option></select><input type="date" aria-label="Attendance date"/></div>}<EmptyState icon={page==='attendance'?ClipboardCheck:page==='current-session'?Monitor:ShieldCheck} title={page==='attendance'?'No attendance records':page==='current-session'?'You’re not in a session':'No active classroom permissions'} description={page==='attendance'?'Attendance records will appear after classroom sessions are connected.':page==='current-session'?'Your current class, attendance, and session details will appear here when a teacher starts a connected session.':'Application permissions will appear during a connected classroom session. No applications are currently being controlled.'}>{role==='teacher'&&<Button variant="outline" asChild><Link to="/teacher/start-class"><Play/>Prepare a class</Link></Button>}</EmptyState></Panel>
 :report||feed?<Panel title={title} subtitle={report?'Classroom reports and insights':'Classroom updates'}><div className="table-toolbar"><div className="segmented-control">{(report?['All','This week','This month']:page==='alerts'||page==='notifications'?['All','Unread']:['All','Today']).map(x=><Button key={x} variant={tab===x?'secondary':'ghost'} size="sm" onClick={()=>setTab(x)}>{x}</Button>)}</div><label className="search-input"><Search size={17}/><input placeholder={report?'Search reports…':'Search activity…'} value={query} onChange={e=>setQuery(e.target.value)}/></label></div><EmptyState title={query?'No matching results':report?'No reports yet':page==='alerts'?'No classroom alerts':page==='notifications'?'You’re all caught up':page==='live-activity'?'No active classroom session':'No activity yet'} description={report?'Reports will appear here when classroom sessions and reporting services are connected.':page==='alerts'?'Alerts from connected classroom sessions will appear here.':page==='notifications'?'Updates from your classes will appear once your institution is connected.':'Activity will appear when your classroom is connected. No student or device activity is being monitored.'} icon={report?Sparkles:page==='alerts'||page==='notifications'?Bell:Activity}/></Panel>:null}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogTitle>{page==='faculty-allocation'?'Allocate faculty':`Add ${dir?.name}`}</DialogTitle><DialogDescription>Prepare the details below. Saving records is unavailable until your institution is connected.</DialogDescription><form className="modal-form" onSubmit={e=>e.preventDefault()}>{page==='faculty-allocation'?<><Field label="Teacher"><select disabled><option>No teachers available</option></select></Field><Field label="Class"><select disabled><option>No classes available</option></select></Field><Field label="Subject"><select disabled><option>No subjects available</option></select></Field></>:<><Field label={page==='students'||page==='teachers'?'Full name':`${dir?.name} name`}><input placeholder="Enter a name" required/></Field>{page==='students'||page==='teachers'?<Field label="Email address"><input type="email" placeholder="name@institution.edu" required/></Field>:<Field label="Code"><input placeholder="Enter a code"/></Field>}<Field label={page==='students'?'Student ID':'Department'}><input placeholder={page==='students'?'Enter student ID':'Department name'}/></Field></>}<div className="flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setDialog(false)}>Cancel</Button><Button disabled>Save unavailable</Button></div></form></DialogContent></Dialog><Dialog open={notice} onOpenChange={setNotice}><DialogContent><DialogTitle>Workspace not connected</DialogTitle><DialogDescription>Your changes have not been saved. Account and institution settings will become available after the backend is connected.</DialogDescription><Button onClick={()=>setNotice(false)} className="justify-self-end">Got it</Button></DialogContent></Dialog></>
}
